# Generated by Django 3.1.3 on 2021-07-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210705_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=64, verbose_name='Contraseña'),
        ),
    ]
