# Generated by Django 3.1.3 on 2021-07-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Contraseña'),
        ),
    ]
