# Generated by Django 3.1.3 on 2021-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha creacion :'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha actualizacion: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion :'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion: '),
        ),
    ]
