# Generated by Django 3.1.3 on 2021-07-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20210711_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Personal de la empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Personal de la empresa'),
        ),
    ]
