# Generated by Django 3.1.3 on 2021-07-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20210711_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'last_name', 'email')},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
