# Generated by Django 3.1.3 on 2021-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20210715_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado de usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado de usuario'),
        ),
    ]
