# Generated by Django 3.1.3 on 2021-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20210713_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_state',
            field=models.CharField(choices=[('0', 'SELECCIONAR'), ('1', 'TARJETA'), ('2', 'METALICO'), ('3', 'CONTRAREEMBOLSO')], default='0', max_length=30, verbose_name='Estado del pago: '),
        ),
    ]
