# Generated by Django 3.1.3 on 2021-07-05 02:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Descripcion producto')),
                ('g_model', models.CharField(choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], max_length=30, verbose_name='Género')),
                ('color_model', models.CharField(choices=[('ROJO', 'ROJO'), ('VERDE', 'VERDE'), ('NARANJA', 'NARANJA'), ('AMARILLO', 'AMARILLO'), ('BLANCO', 'BLANCO'), ('NEGRO', 'NEGRO'), ('MARRON', 'MARRON')], max_length=30, verbose_name='Color')),
                ('size_model', models.CharField(choices=[('ROJO', 'ROJO'), ('VERDE', 'VERDE'), ('NARANJA', 'NARANJA'), ('AMARILLO', 'AMARILLO'), ('BLANCO', 'BLANCO'), ('NEGRO', 'NEGRO'), ('MARRON', 'MARRON')], max_length=30, verbose_name='Talla')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
