# Generated by Django 3.1.3 on 2021-07-11 06:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_order', models.DateTimeField(verbose_name='Tipo de Venta')),
                ('product_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('brand', models.CharField(choices=[('0', 'MARCA1'), ('1', 'MARCA2'), ('2', 'MARCA3'), ('3', 'MARCA4'), ('4', 'MARCA5'), ('5', 'MARCA6')], max_length=30, verbose_name='Marca')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=300, verbose_name='Descripcion producto')),
                ('g_model', models.CharField(choices=[('0', 'HOMBRE'), ('1', 'MUJER'), ('2', 'OTROS')], max_length=30, verbose_name='Genero')),
                ('color_model', models.CharField(choices=[('1', 'ROJO'), ('2', 'VERDE'), ('3', 'NARANJA'), ('4', 'AMARILLO'), ('5', 'BLANCO'), ('6', 'NEGRO'), ('7', 'MARRON')], max_length=30, verbose_name='Color')),
                ('size_model', models.CharField(choices=[('0', '32'), ('1', '34'), ('2', '36'), ('3', '38'), ('4', '40'), ('5', '42'), ('6', '44'), ('7', '46')], max_length=30, verbose_name='Talla')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('num_sales', models.PositiveIntegerField(default=0, verbose_name='Unidades vendidas')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
