# Generated by Django 3.1.3 on 2021-07-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_order',
        ),
    ]
