# Generated by Django 3.1.3 on 2021-07-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_product_date_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='g_model',
            field=models.CharField(choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER'), ('2', 'OTROS')], max_length=30, verbose_name='Genero'),
        ),
    ]
