# Generated by Django 3.1.3 on 2021-07-13 14:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210712_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=300, verbose_name='Descripcion producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_sales',
            field=models.IntegerField(default=0, verbose_name='Unidades vendidas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
