# Generated by Django 3.1.3 on 2021-07-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20210713_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_model',
            field=models.CharField(choices=[('0', 'ROJO'), ('1', 'VERDE'), ('2', 'NARANJA'), ('3', 'AMARILLO'), ('4', 'BLANCO'), ('5', 'NEGRO'), ('6', 'MARRON')], max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='g_model',
            field=models.CharField(choices=[('0', 'HOMBRE'), ('1', 'MUJER'), ('2', 'OTROS')], max_length=30, verbose_name='Genero'),
        ),
    ]
