# Generated by Django 3.1.3 on 2021-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210713_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('0', 'SELECCIONAR...'), ('1', 'MARCA1'), ('2', 'MARCA2'), ('3', 'MARCA3'), ('4', 'MARCA4'), ('5', 'MARCA5'), ('6', 'MARCA6')], max_length=30, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_model',
            field=models.CharField(choices=[('0', 'SELECCIONAR...'), ('1', 'ROJO'), ('2', 'VERDE'), ('3', 'NARANJA'), ('4', 'AMARILLO'), ('5', 'BLANCO'), ('6', 'NEGRO'), ('7', 'MARRON')], max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='g_model',
            field=models.CharField(choices=[('0', 'SELECCIONAR...'), ('1', 'HOMBRE'), ('2', 'MUJER'), ('3', 'OTROS')], max_length=30, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_model',
            field=models.CharField(choices=[('0', 'SELECCIONAR...'), ('1', '32'), ('2', '34'), ('3', '36'), ('4', '38'), ('5', '40'), ('6', '42'), ('7', '44'), ('8', '46')], max_length=30, verbose_name='Talla'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
